### ISSUE TITLE
About Page Credits Update

### ISSUE THREAD

**Issue by bennettforkner** [gordon-cs/gordon-360-ui#1118]
The "Beneficent Philanthropes" section of the '[About](https://360train.gordon.edu/about)' page will have to be updated as Dr. Lindsay heads out and we welcome Dr. Mike Hammond as our new President this summer. Not sure what changes exactly we would want to make, it might be a little bit insincere to just replace the names. I would love to hear input from @ChrisImagineer .

Also, Jennifer Jukanovich is no longer the VP for student life. Dan Tymann is the current VP for Campus Life since 2019.

**Comment by ChrisImagineer** [comment]
Thanks, Bennett.
I’ve thought about this history section, and you’re right that there have been transitions. Despite making it longer, maybe we can re-write it to have a “History” section, with the initial admins and benefactors listed in that one mini-section. And then a “Current Benefactors” section for the current VP and President and donors. And then every once in a while we just move some people to the “History” section?

I just felt there should always be a nod to benefactors and those who allowed crazy ideas to go forward.
What do you think?

On 05/12/21, 01:29, "Bennett F Forkner" ***@***.******@***.***>> wrote:


The "Beneficent Philanthropes" section of the 'About<https://360.gordon.edu/about>' page will have to be updated as Dr. Lindsay heads out and we welcome Dr. Mike Hammond as our new President this summer. Not sure what changes exactly we would want to make, it might be a little bit insincere to just replace the names. I would love to hear input from @ChrisImagineer<https://github.com/ChrisImagineer> .

Also, Jennifer Jukanovich is no longer the VP for student life. Dan Tymann is the current VP for Campus Life since 2019.

**Comment by bennettforkner** [comment]
@ChrisImagineer I definitely agree. Keeping the history of Jennifer and Dr. Lindsay's support is very important. We can work on wording in the coming few weeks as the transition moves forward.

**Comment by roddy3** [comment]
Hello Chris, 

I was reading through the description of the problem here, I really like your idea on keeping our history and then updating them as we go but I am still puzzled on what you want it to look like, correct me if I am wrong you wanted to change "Origins" to "History" and then have another section "Current Benefactors" that would have all the new updates of the campus like the current VP, The President and The donors...  is this what you meant? sorry if I repeat myself just trying to picture the solution.

**Comment by ChrisImagineer** [comment]
﻿Excellent questions; sorry we didn’t provide more context. We were talking this out and added a card in the github deck, but haven’t solved it.

Maybe its simpler to work with what we have than spend time re-creating a minor component?
1 Change “Origins” to its own section, standing alone.

2 Create a new section (new separator) for “GoCo Tech Lab Developers,” and group all the running years of teams under that heading and we’ll keep it going that way.

3 Move the “Beneficient Phialthropes” section to the Origins section (last list of that section), Heading “Benefactors and Contributors.” In one paragraph:
We’re continually grateful to the many visionary contributors and benefactors who support both the Summer Practicum in Computer Science and the ongoing efforts of GoCo Tech Labs. Thanks to all of our mentors and coaches in development and deployment for your guidance, advice, and encouragement to try new things.

(That last part should take care of the record-keeping on presidents and vp’s!)


On 06/03/21, 13:53, "Roddy3" ***@***.******@***.***>> wrote:


Hello Chris,

I was reading through the description of the problem here, I really like your idea on keeping our history and then updating them as we go but I am still puzzled on what you want it to look like, correct me if I am wrong you wanted to change "Origins" to "History" and then have another section "Current Benefactors" that would have all the new updates of the campus like the current VP, The President and The donors... is this what you meant? sorry if I repeat myself just trying to picture the solution.

**Comment by roddy3** [comment]
@ChrisImagineer, ![Screen Shot 2021-06-03 at 4 32 04 PM](https://user-images.githubusercontent.com/60272749/120709137-7a38b600-c48a-11eb-86df-0a6b6f39698f.png)I finished modifying the About page, I think I did what you asked me to do would you mind taking a look at it to make sure it is done the way it was supposed to be? ![Screen Shot 2021-06-03 at 4 31 43 PM](https://user-images.githubusercontent.com/60272749/120709170-845ab480-c48a-11eb-8f43-b337d622516c.png)Here is the screen shot of how it looks like,![Screen Shot 2021-06-03 at 4 31 25 PM (2)](https://user-images.githubusercontent.com/60272749/120709223-90467680-c48a-11eb-927a-e728f4ae9c50.png)

**Comment by ChrisImagineer** [comment]
Yes! That’ll do nicely. Thank you, Roddy3

On 06/03/21, 16:41, "Roddy3" ***@***.******@***.***>> wrote:


@ChrisImagineer<https://github.com/ChrisImagineer>, [Screen Shot 2021-06-03 at 4 32 04 PM] <https://user-images.githubusercontent.com/60272749/120709137-7a38b600-c48a-11eb-86df-0a6b6f39698f.png> I finished modifying the About page, I think I did what you asked me to do would you mind taking a look at it to make sure it is done the way it was supposed to be? [Screen Shot 2021-06-03 at 4 31 43 PM] <https://user-images.githubusercontent.com/60272749/120709170-845ab480-c48a-11eb-8f43-b337d622516c.png> Here is the screen shot of how it looks like,[Screen Shot 2021-06-03 at 4 31 25 PM (2)]<https://user-images.githubusercontent.com/60272749/120709223-90467680-c48a-11eb-927a-e728f4ae9c50.png>

**Comment by bennettforkner** [comment]
That looks great Roddy!

Could you make sure that “Origins” is capitalized in the final version? Thanks!

Blessings,

Bennett Forkner
***@***.***



On Jun 3, 2021, at 17:51, ChrisImagineer ***@***.***> wrote:

﻿
Yes! That’ll do nicely. Thank you, Roddy3 

On 06/03/21, 16:41, "Roddy3" ***@***.******@***.***>> wrote: 


@ChrisImagineer<https://github.com/ChrisImagineer>, [Screen Shot 2021-06-03 at 4 32 04 PM] <https://user-images.githubusercontent.com/60272749/120709137-7a38b600-c48a-11eb-86df-0a6b6f39698f.png> I finished modifying the About page, I think I did what you asked me to do would you mind taking a look at it to make sure it is done the way it was supposed to be? [Screen Shot 2021-06-03 at 4 31 43 PM] <https://user-images.githubusercontent.com/60272749/120709170-845ab480-c48a-11eb-8f43-b337d622516c.png> Here is the screen shot of how it looks like,[Screen Shot 2021-06-03 at 4 31 25 PM (2)]<https://user-images.githubusercontent.com/60272749/120709223-90467680-c48a-11eb-927a-e728f4ae9c50.png>
