### ISSUE TITLE
Allow searching by maiden name

### ISSUE THREAD

**Issue by jsenning** [gordon-cs/gordon-360-ui#1229]
Just as we now match the first name field to either a person's first name or their nickname, we should match the last name field to a person's last name or their maiden name (if any).

**Comment by russtuck** [comment]
API is done.  UI is still to do.

**Comment by russtuck** [comment]
Search results do show up in UI, but doesn't show the maiden name.  So there can be results that don't appear to match, since maiden name is invisible.  The maiden name should always be shown, since it is always a potential search match.

Full name format: 
  Firstname (Nickname) Lastname (Maidenname)
