### ISSUE TITLE
Page title stays as "Login | Gordon 360" after logging in and being redirected to the homepage

### ISSUE THREAD

**Issue by bennettforkner** [gordon-cs/gordon-360-ui#1444]
The tab header of the site should be "Home | Gordon 360" after you log in and are redirected to the home page, but it stays as the "Login..." title.

**Comment by EjPlatzer** [comment]
This is a quirk of the current state of our login process. Because the login "page" is currently a component on the homepage that is conditionally displayed, there is no navigation involved in logging in. The page title normally only changes on page navigation, via the hook [`useDocumentTitle`](https://github.com/gordon-cs/gordon-360-ui/blob/bc13e33cd9f41803518073d3d2e941a858ff21b7/src/hooks/useDocumentTitle.js) in [`src/components/Header/index.js`](https://github.com/gordon-cs/gordon-360-ui/blob/30dda662b2311d3fe64353300e7617e1e017c71d/src/components/Header/index.js#L172). However, in [`src/views/Home/components/GuestWelcome/index.js`](https://github.com/gordon-cs/gordon-360-ui/blob/e190428ee2016bc37f7c9524c4acc48ebd291f8a/src/views/Home/components/GuestWelcome/index.js#L18), the document title is manually set when the component loads. This means that the title stays "Login..." even after the user has logged in as long as they stay on the Home route.

This does not significantly degrade the user experience, but it is easy to fix in a number of ways. The long-term goal is to make the `LoginDialogue` component a true Dialogue that can be displayed on any page, which would no longer require it to update the document title. The simple short-term solutions are to remove the manual update to document title in `GuestWelcome`, or to reset the document title in the cleanup function of the useEffect that changes it.

**Comment by EjPlatzer** [comment]
Now that Azure SSO is implemented, this has been fixed.
