### ISSUE TITLE
Paginate Events

### ISSUE THREAD

**Issue by bennettforkner** [gordon-cs/gordon-360-ui#1555]
The events page currently shows all of the events in the next year when requested. This is a lot of overhead to handle (although the UI seems to do pretty well for me) and it is a lot of data to show on one page.

I think the very least we could do for UX is to paginate the events list (in the UI or both) so that we are not showing a giant list of events that the user most likely does not care about. I welcome @ChrisImagineer 's thoughts as well, of course.

**Comment by ChrisImagineer** [comment]
I like your idea about the “show 10 evens” show 20 events, etc. Its better for a quick snapshot and for mobile users.
Or, “show today” show tomorrow, show this week”

Should we also refine the filters for users? If we did, take a quick look at the types of events listed in 25Live. Are there some for which students would just not want to know about, or do we need an event type that is more student focused – so a “Meeting” of a student club reservation, but tat is also “Student Activity” type that might not yet exist > can more than one “type” or category of  event be used, could there be tags? (don’t pursue this if this is a waste of time this summer)

25Live is a facility schedule calendar, but we’re using it as an event calendar too, but its not great at that.
Chris

On 2024/5/24, 14:12, "dli505" ***@***.******@***.***>> wrote:


Some thoughts and notes:
·         it seems like the actual amount of events loaded is only for a year (e.g., right now it shows events from today till commencement 2025), and when past events are included it only includes events for the past year, so right now it would show events for the 23-24 year and 24-25 year, which isn't as daunting as I thought it would be
·         showing all the events at once seems okay on computer, if a user wants to find events that are, say, within December, they only need to scroll down to the section of events during December and find it that way. If, however, events were to be paginated, it would be a little harder to guess where events that happen during a specified time would be, although, I suppose on mobile it might be annoying to scroll that much
·         perhaps instead of pagination we could have something like "show 25 events", "show 50 events", "show all events"? Might be more ideal, not sure
