### ISSUE TITLE
People search is not showing alumni before 2002

### ISSUE THREAD

**Issue by jsenning** [gordon-cs/gordon-360-ui#1615]
After summer 2021 we were able to look alumni using people search.  Clicking on the results often didn't work since most alumni don't have profiles, but at least they showed up in the search results.  Many of those same alumni no longer show up.  Examples include Patrick Truitt (2001), Robert Truitt (1993), Karen (Truitt) Senning (1986), as well as others.

I wonder if we're just not showing alums that don't have a profile.  I think we should show them, but perhaps replace the link to their profile with a link to a page that indicates no profile exists.

**Comment by russtuck** [comment]
If there's no profile page, then the result could not have a link at all
(since there's nothing to link to).  Or, we could create a profile page
with just the same info as the result.

**Comment by bennettforkner** [comment]
> If there's no profile page, then the result could not have a link at all (since there's nothing to link to). Or, we could create a profile page with just the same info as the result.

I personally like this option. I believe @EjPlatzer proposed at some point suggested that we factor out user names to be their own component. Then we could make every instance of a name link in the same way to their profile (or not link to anything). We would have to consider how to do this without loosing too much efficiency in loading the page, though, doing a `profile exists?` lookup for each of the search results could get expensive fast.

**Comment by bennettforkner** [comment]
Any alumni from before 2002 would not have been in our accounts table in the database. In fact, they never should have showed up in people search in the fact (even on the GO site). @jsenning, are you sure that you were, at one point, able to see these people in people search?

Either way, this ticket is really to consider how we determine who shows up in people search. Currently, a prerequisite is that the person have an account with Gordon, but as Jonathan puts it, we still want to show people if they do not have an account.

**Comment by Kevin-Chu58** [comment]
@bennettforkner I think I was the one that made some changes to Advanced People Search during the CS Summer Practicum 2021. We made an update that generated profiles for alumni who don't have an adusername, and instead, we used encrypted ID to access their profile.

**Comment by russtuck** [comment]
We used Karen Senning as an example in the final presentation of the summer practicum when Kevin worked on it.  So yes, I'm certain that it worked for her.  I might even be able to find a video of the demonstration.

**Comment by bennettforkner** [comment]
> We used Karen Senning as an example in the final presentation of the summer practicum when Kevin worked on it.  So yes, I'm certain that it worked for her.  I might even be able to find a video of the demonstration.  

I believe you! :)

**Comment by EjPlatzer** [comment]
Ok, after a bit of git history sleuthing and database investigation, I've tracked down 2 changes that contribute to these accounts no longer appearing in People Search.
1. When we upgraded to .NET 6 from .NET Framework 4.8, I removed the process that cached all profile data when the API started up and every 4 minutes afterward. That process executed a SQL statement that existed as an string literal in the API to retrieve said account data. It was also error-prone and the cause of unpredictable but frequent crashes of the API.
 When I replaced this process, I had the API just query the database directly (via our ORM) for profile data as needed. However, in the process I removed the inline SQL statements, without remembering that the one for retrieving Alumni had a special process for handling Alumni without an Active Directory Username. This resulted in said users remaining in the underlying dataset but without a value for the Username column. The result was that said accounts broke the frontend when they tried to load.
2. In response to these accounts breaking the frontend, several months later, @bennettforkner and I added a clause to the profile data views in 360's database to exclude all accounts without an AD Username so that they effectively would not exist in our dataset, thereby preventing them from breaking the site.

One potential solution is to restore the process that the 2021 Summer Practicum students introduced to handle these account-less people, namely creating a Hash of the user's ID to stand in as their AD Username. However, because of the changed architecture, this change would be most cleanly introduced within the views themselves, rather than in a query result set relevant only to People Search.

I think that solution is worth testing in Train, both to make sure it works as expected, and to be sure it doesn't have any unintended side effects (such as breaking the site on trying to visit the profile of such users). Thoughts @jsenning @russtuck ?

**Comment by jsenning** [comment]
To make sure I understand, are you suggesting that we create entries in the view of the database for all alumni that do not have AD usernames?  If so, does that mean that it could (someday) be possible for alumni to have & maintain profiles on 360 -- or at least have some control on whether they will show up in search results.

**Comment by EjPlatzer** [comment]
> To make sure I understand, are you suggesting that we create entries in the view of the database for all alumni that do not have AD usernames?
Not exactly. I'm suggesting that we add a value for the AD Username column, not create an entirely new row.

> If so, does that mean that it could (someday) be possible for alumni to have & maintain profiles on 360 -- or at least have some control on whether they will show up in search results.
This would certainly be possible, but it would also be unrelated to any efforts on this particular issue.

**Comment by Dopey12** [comment]
This appears to be working. Is there anything left to do?
