### ISSUE TITLE
Security: Privacy Flaw

### ISSUE THREAD

**Issue by Centerville1** [gordon-cs/gordon-360-ui#1928]
There is a privacy flaw in the UI where users can change a single line of code via browser devtools and view normally hidden buttons and info.  On the involvements page, it is possible to change the code that checks if a user is an admin, and it will show members of a club (even when you aren't in the club) and the admin involvements editing buttons.  It is also possible to view other student's schedule panels by changing the myProf check in the public profile page, to view the private schedule info as a student.

**Comment by EjPlatzer** [comment]
Thanks for documenting this! This is actually reflective of an issue in the API. It will always be true that users can edit the code an the front end and, for example, make themselves an admin. However, it should be impossible for them to access any data that they aren't supposed to be able to, because the API does all authorization / data privacy checks, and it performs those authorization checks independent of the state of the UI.
