### ISSUE TITLE
Accessability issue on schedule section of profile.

### ISSUE THREAD

**Issue by hd7970** [gordon-cs/gordon-360-ui#2137]
When navigating through schedule section via keyboard, you can only select the first course of each day.

**Comment by Luke-W-Hart** [comment]
It seems you can navigate through the courses but can't press enter when your focused on them to add them to your calendar. 
Also pressing tab doesn't navigate to the "ONLN ASYNC" but these aren't really necessary to add to your calendar (since there's no set meeting time) so I would assume that's fine.
