### ISSUE TITLE
Add a link to the yearbook website

### ISSUE THREAD

**Issue by NathanielRudenberg** [gordon-cs/gordon-360-ui#391]
The yearbook club would like us to add a link to the TreeRing website to allow students to buy yearbooks.

**Comment by ChrisImagineer** [comment]
Actually - they could just add that link in their Group page.
(Principle: 360 is not a StuGov website, but a landing and launching spot for Groups and personal campus general information. Let's use the Group info on a page to let the group market and direct as they like. Otherwise, every group will want space for their own links and that'll be a nightmare. #ifonlyGCSAhadawebstrategy
