### ISSUE TITLE
faculty meal balance is always $0

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#420]
Sometime after May 1, my meal balance quit being displayed correctly.  Now it is always 0.

**Comment by russtuck** [comment]
This might be related to ending the spring term and entering the summer term.

**Comment by jsenning** [comment]
This has been fixed.  The hash seed used when connecting to Bon Appetit's server was changed.  We also changed logic so that, regardless of user role (student, facstaff, etc.), if there is meal plan then all meal plan info for the current session is reported.  If there is no meal plan a check is made to see if there is a fac-staff cash balance.

**Comment by jsenning** [comment]
Issue is closed.
