### ISSUE TITLE
problems for retired faculty

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#880]
Prof. Bjork is newly retired, and reports that the health check hangs (spinner) when he logs in.  (He logged out and back in, refreshed the page, and tried with different browsers, with no change.)  He reports further:

The tabs work even with the spinning wheel going.

Home keeps me on the spinning wheel.
Involvements gives me two spinning wheels - one each for my involvements and all involvements
Events appears to work correctly - gives me a list
People works fine.  When I search for Russell Tuck, I get correct information.  When I search for Russell Bjork, I get “No results found” - so presumably it is using the  up-to-date database.  
Wellness gives me a big red X.

**Comment by bennettforkner** [comment]
Retired/Resigned faculty/staff are not included in people search and do not have access to 360. Retired faculty/staff retain access to their email, but will have no limited/no access to 360 unless they are alumni.

Some events are public, so they will always show up for any user.

Wellness check is disabled indefinitely, so that will not be an issue.
